-- Create alerts table for follow-up notifications
-- This table stores alerts generated by the automation system

CREATE TABLE IF NOT EXISTS alerts (
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    tenant_key VARCHAR(50) NOT NULL DEFAULT 'rabin',
    type ENUM('warning', 'info', 'urgent', 'success') NOT NULL DEFAULT 'warning',
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    lead_id VARCHAR(36) NULL,
    lead_name VARCHAR(255) NULL,
    priority ENUM('high', 'medium', 'low') NOT NULL DEFAULT 'medium',
    is_read BOOLEAN DEFAULT FALSE,
    days_overdue INT NULL,
    created_by VARCHAR(36) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP NULL,
    dismissed_at TIMESTAMP NULL,
    
    INDEX idx_tenant_key (tenant_key),
    INDEX idx_lead_id (lead_id),
    INDEX idx_priority (priority),
    INDEX idx_is_read (is_read),
    INDEX idx_created_at (created_at),
    
    FOREIGN KEY (lead_id) REFERENCES customers(id) ON DELETE CASCADE
);

-- Insert some sample alerts for testing
INSERT INTO alerts (tenant_key, type, title, message, lead_id, priority, days_overdue) VALUES
('rabin', 'warning', 'سرنخ نیاز به پیگیری دارد', 'علی احمدی بیش از 5 روز پیگیری نشده است', NULL, 'high', 5),
('rabin', 'urgent', 'سرنخ داغ عقب‌افتاده', 'شرکت رابین (سرنخ داغ) بیش از 3 روز پیگیری نشده است', NULL, 'high', 3),
('rabin', 'info', 'مرحله جدید', 'سرنخ جدید در مرحله تماس اولیه قرار گرفت', NULL, 'medium', 0);